### ISSUE TITLE
Similar project github-dependents-info

### ISSUE THREAD

**Issue by nvuillam** [jtmiclat/github-download-dependents-info#2]
Hi,

I created a similar project some time ago, it's also in python and has more features (not CSV yet but JSON & markdown & badges) , so if you want to contribute you are very welcome :)

https://github.com/nvuillam/github-dependents-info

Best regards

Nicolas

**Comment by jtmiclat** [comment]
Great job on your project! It looks way more complete. Added a link your project in the README!
